#!/bin/bash
#MOAB -A farrw01
#MOAB -j oe
#MOAB -N kepler-selection
#MOAB -d /gpfs/bb/farrw/selection/kepler-selection
#MOAB -l walltime=48:0:0
#MOAB -l nodes=1:ppn=16

module unload apps/openmpi

python run.py --candidates ../Kepler/candidates.dat.bz2 --systems ../Kepler/systems.dat.bz2 --outdir ../Kepler --threads 15 --walkers 512
